// Code generated by entc, DO NOT EDIT.

package productspecsitem

import (
	"time"
)

const (
	// Label holds the string label denoting the productspecsitem type in the database.
	Label = "product_specs_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProductSpecsID holds the string denoting the product_specs_id field in the database.
	FieldProductSpecsID = "product_specs_id"
	// FieldValueID holds the string denoting the value_id field in the database.
	FieldValueID = "value_id"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// EdgeSpecs holds the string denoting the specs edge name in mutations.
	EdgeSpecs = "specs"
	// EdgeValues holds the string denoting the values edge name in mutations.
	EdgeValues = "values"
	// Table holds the table name of the productspecsitem in the database.
	Table = "product_specs_item"
	// SpecsTable is the table that holds the specs relation/edge.
	SpecsTable = "product_specs_item"
	// SpecsInverseTable is the table name for the ProductSpecs entity.
	// It exists in this package in order to avoid circular dependency with the "productspecs" package.
	SpecsInverseTable = "product_specs"
	// SpecsColumn is the table column denoting the specs relation/edge.
	SpecsColumn = "product_specs_id"
	// ValuesTable is the table that holds the values relation/edge. The primary key declared below.
	ValuesTable = "product_specs_item_values"
	// ValuesInverseTable is the table name for the ProductAttributeValue entity.
	// It exists in this package in order to avoid circular dependency with the "productattributevalue" package.
	ValuesInverseTable = "product_attribute_value"
)

// Columns holds all SQL columns for productspecsitem fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProductSpecsID,
	FieldValueID,
	FieldSort,
}

var (
	// ValuesPrimaryKey and ValuesColumn2 are the table columns denoting the
	// primary key for the values relation (M2M).
	ValuesPrimaryKey = []string{"product_specs_item_id", "product_attribute_value_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
