// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MenuColumns holds the columns for the "menu" table.
	MenuColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "pid", Type: field.TypeInt, Nullable: true},
		{Name: "tree", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "title", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "level", Type: field.TypeInt, Default: 1},
		{Name: "sort", Type: field.TypeInt, Default: 1},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"0", "1"}},
		{Name: "icon", Type: field.TypeString, Nullable: true},
		{Name: "hidden", Type: field.TypeEnum, Nullable: true, Enums: []string{"0", "1"}},
		{Name: "desc", Type: field.TypeString, Nullable: true},
		{Name: "menu_prev", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// MenuTable holds the schema information for the "menu" table.
	MenuTable = &schema.Table{
		Name:       "menu",
		Columns:    MenuColumns,
		PrimaryKey: []*schema.Column{MenuColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "menu_menu_prev",
				Columns:    []*schema.Column{MenuColumns[14]},
				RefColumns: []*schema.Column{MenuColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "menu_url",
				Unique:  false,
				Columns: []*schema.Column{MenuColumns[7]},
			},
			{
				Name:    "menu_id",
				Unique:  true,
				Columns: []*schema.Column{MenuColumns[0]},
			},
		},
	}
	// OrderColumns holds the columns for the "order" table.
	OrderColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "sn", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Nullable: true, Enums: []string{"0", "10", "20", "30", "40", "50", "60", "70", "80", "90"}, Default: "0"},
	}
	// OrderTable holds the schema information for the "order" table.
	OrderTable = &schema.Table{
		Name:       "order",
		Columns:    OrderColumns,
		PrimaryKey: []*schema.Column{OrderColumns[0]},
	}
	// OrderPayColumns holds the columns for the "order_pay" table.
	OrderPayColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "create_id", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "sn", Type: field.TypeString, Unique: true},
		{Name: "price", Type: field.TypeFloat64, Default: 0},
		{Name: "pay_mode", Type: field.TypeString, Nullable: true},
		{Name: "order_pay", Type: field.TypeInt, Nullable: true},
	}
	// OrderPayTable holds the schema information for the "order_pay" table.
	OrderPayTable = &schema.Table{
		Name:       "order_pay",
		Columns:    OrderPayColumns,
		PrimaryKey: []*schema.Column{OrderPayColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "order_pay_order_pay",
				Columns:    []*schema.Column{OrderPayColumns[8]},
				RefColumns: []*schema.Column{OrderColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MenuTable,
		OrderTable,
		OrderPayTable,
	}
)

func init() {
	MenuTable.ForeignKeys[0].RefTable = MenuTable
	MenuTable.Annotation = &entsql.Annotation{
		Table: "menu",
	}
	OrderPayTable.ForeignKeys[0].RefTable = OrderTable
}
