// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orse/ent/order"
	"orse/ent/orderpay"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderPayCreate is the builder for creating a OrderPay entity.
type OrderPayCreate struct {
	config
	mutation *OrderPayMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (opc *OrderPayCreate) SetCreatedAt(t time.Time) *OrderPayCreate {
	opc.mutation.SetCreatedAt(t)
	return opc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (opc *OrderPayCreate) SetNillableCreatedAt(t *time.Time) *OrderPayCreate {
	if t != nil {
		opc.SetCreatedAt(*t)
	}
	return opc
}

// SetUpdatedAt sets the "updated_at" field.
func (opc *OrderPayCreate) SetUpdatedAt(t time.Time) *OrderPayCreate {
	opc.mutation.SetUpdatedAt(t)
	return opc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (opc *OrderPayCreate) SetNillableUpdatedAt(t *time.Time) *OrderPayCreate {
	if t != nil {
		opc.SetUpdatedAt(*t)
	}
	return opc
}

// SetUserID sets the "user_id" field.
func (opc *OrderPayCreate) SetUserID(i int) *OrderPayCreate {
	opc.mutation.SetUserID(i)
	return opc
}

// SetCreateID sets the "create_id" field.
func (opc *OrderPayCreate) SetCreateID(i int) *OrderPayCreate {
	opc.mutation.SetCreateID(i)
	return opc
}

// SetNillableCreateID sets the "create_id" field if the given value is not nil.
func (opc *OrderPayCreate) SetNillableCreateID(i *int) *OrderPayCreate {
	if i != nil {
		opc.SetCreateID(*i)
	}
	return opc
}

// SetSn sets the "sn" field.
func (opc *OrderPayCreate) SetSn(s string) *OrderPayCreate {
	opc.mutation.SetSn(s)
	return opc
}

// SetPrice sets the "price" field.
func (opc *OrderPayCreate) SetPrice(f float64) *OrderPayCreate {
	opc.mutation.SetPrice(f)
	return opc
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (opc *OrderPayCreate) SetNillablePrice(f *float64) *OrderPayCreate {
	if f != nil {
		opc.SetPrice(*f)
	}
	return opc
}

// SetPayMode sets the "pay_mode" field.
func (opc *OrderPayCreate) SetPayMode(s string) *OrderPayCreate {
	opc.mutation.SetPayMode(s)
	return opc
}

// SetNillablePayMode sets the "pay_mode" field if the given value is not nil.
func (opc *OrderPayCreate) SetNillablePayMode(s *string) *OrderPayCreate {
	if s != nil {
		opc.SetPayMode(*s)
	}
	return opc
}

// SetOwnerID sets the "owner" edge to the Order entity by ID.
func (opc *OrderPayCreate) SetOwnerID(id int) *OrderPayCreate {
	opc.mutation.SetOwnerID(id)
	return opc
}

// SetOwner sets the "owner" edge to the Order entity.
func (opc *OrderPayCreate) SetOwner(o *Order) *OrderPayCreate {
	return opc.SetOwnerID(o.ID)
}

// Mutation returns the OrderPayMutation object of the builder.
func (opc *OrderPayCreate) Mutation() *OrderPayMutation {
	return opc.mutation
}

// Save creates the OrderPay in the database.
func (opc *OrderPayCreate) Save(ctx context.Context) (*OrderPay, error) {
	var (
		err  error
		node *OrderPay
	)
	opc.defaults()
	if len(opc.hooks) == 0 {
		if err = opc.check(); err != nil {
			return nil, err
		}
		node, err = opc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderPayMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = opc.check(); err != nil {
				return nil, err
			}
			opc.mutation = mutation
			if node, err = opc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(opc.hooks) - 1; i >= 0; i-- {
			if opc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = opc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, opc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (opc *OrderPayCreate) SaveX(ctx context.Context) *OrderPay {
	v, err := opc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (opc *OrderPayCreate) Exec(ctx context.Context) error {
	_, err := opc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opc *OrderPayCreate) ExecX(ctx context.Context) {
	if err := opc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (opc *OrderPayCreate) defaults() {
	if _, ok := opc.mutation.CreatedAt(); !ok {
		v := orderpay.DefaultCreatedAt()
		opc.mutation.SetCreatedAt(v)
	}
	if _, ok := opc.mutation.UpdatedAt(); !ok {
		v := orderpay.DefaultUpdatedAt()
		opc.mutation.SetUpdatedAt(v)
	}
	if _, ok := opc.mutation.CreateID(); !ok {
		v := orderpay.DefaultCreateID
		opc.mutation.SetCreateID(v)
	}
	if _, ok := opc.mutation.Price(); !ok {
		v := orderpay.DefaultPrice
		opc.mutation.SetPrice(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (opc *OrderPayCreate) check() error {
	if _, ok := opc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "user_id"`)}
	}
	if _, ok := opc.mutation.Sn(); !ok {
		return &ValidationError{Name: "sn", err: errors.New(`ent: missing required field "sn"`)}
	}
	if _, ok := opc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "price"`)}
	}
	if _, ok := opc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner", err: errors.New("ent: missing required edge \"owner\"")}
	}
	return nil
}

func (opc *OrderPayCreate) sqlSave(ctx context.Context) (*OrderPay, error) {
	_node, _spec := opc.createSpec()
	if err := sqlgraph.CreateNode(ctx, opc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (opc *OrderPayCreate) createSpec() (*OrderPay, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderPay{config: opc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: orderpay.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: orderpay.FieldID,
			},
		}
	)
	if value, ok := opc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: orderpay.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := opc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: orderpay.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := opc.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: orderpay.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := opc.mutation.CreateID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: orderpay.FieldCreateID,
		})
		_node.CreateID = value
	}
	if value, ok := opc.mutation.Sn(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: orderpay.FieldSn,
		})
		_node.Sn = value
	}
	if value, ok := opc.mutation.Price(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: orderpay.FieldPrice,
		})
		_node.Price = value
	}
	if value, ok := opc.mutation.PayMode(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: orderpay.FieldPayMode,
		})
		_node.PayMode = value
	}
	if nodes := opc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderpay.OwnerTable,
			Columns: []string{orderpay.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: order.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.order_pay = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderPayCreateBulk is the builder for creating many OrderPay entities in bulk.
type OrderPayCreateBulk struct {
	config
	builders []*OrderPayCreate
}

// Save creates the OrderPay entities in the database.
func (opcb *OrderPayCreateBulk) Save(ctx context.Context) ([]*OrderPay, error) {
	specs := make([]*sqlgraph.CreateSpec, len(opcb.builders))
	nodes := make([]*OrderPay, len(opcb.builders))
	mutators := make([]Mutator, len(opcb.builders))
	for i := range opcb.builders {
		func(i int, root context.Context) {
			builder := opcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderPayMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, opcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, opcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, opcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (opcb *OrderPayCreateBulk) SaveX(ctx context.Context) []*OrderPay {
	v, err := opcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (opcb *OrderPayCreateBulk) Exec(ctx context.Context) error {
	_, err := opcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (opcb *OrderPayCreateBulk) ExecX(ctx context.Context) {
	if err := opcb.Exec(ctx); err != nil {
		panic(err)
	}
}
