// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"saas/ent/orderpay"
	"saas/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderPayDelete is the builder for deleting a OrderPay entity.
type OrderPayDelete struct {
	config
	hooks    []Hook
	mutation *OrderPayMutation
}

// Where appends a list predicates to the OrderPayDelete builder.
func (opd *OrderPayDelete) Where(ps ...predicate.OrderPay) *OrderPayDelete {
	opd.mutation.Where(ps...)
	return opd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (opd *OrderPayDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(opd.hooks) == 0 {
		affected, err = opd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderPayMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			opd.mutation = mutation
			affected, err = opd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(opd.hooks) - 1; i >= 0; i-- {
			if opd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = opd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, opd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (opd *OrderPayDelete) ExecX(ctx context.Context) int {
	n, err := opd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (opd *OrderPayDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: orderpay.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: orderpay.FieldID,
			},
		},
	}
	if ps := opd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, opd.driver, _spec)
}

// OrderPayDeleteOne is the builder for deleting a single OrderPay entity.
type OrderPayDeleteOne struct {
	opd *OrderPayDelete
}

// Exec executes the deletion query.
func (opdo *OrderPayDeleteOne) Exec(ctx context.Context) error {
	n, err := opdo.opd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orderpay.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (opdo *OrderPayDeleteOne) ExecX(ctx context.Context) {
	opdo.opd.ExecX(ctx)
}
