// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"orse/ent/predicate"
	"orse/ent/productspecsitem"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductSpecsItemDelete is the builder for deleting a ProductSpecsItem entity.
type ProductSpecsItemDelete struct {
	config
	hooks    []Hook
	mutation *ProductSpecsItemMutation
}

// Where appends a list predicates to the ProductSpecsItemDelete builder.
func (psid *ProductSpecsItemDelete) Where(ps ...predicate.ProductSpecsItem) *ProductSpecsItemDelete {
	psid.mutation.Where(ps...)
	return psid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psid *ProductSpecsItemDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(psid.hooks) == 0 {
		affected, err = psid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductSpecsItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			psid.mutation = mutation
			affected, err = psid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(psid.hooks) - 1; i >= 0; i-- {
			if psid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = psid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, psid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (psid *ProductSpecsItemDelete) ExecX(ctx context.Context) int {
	n, err := psid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psid *ProductSpecsItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: productspecsitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productspecsitem.FieldID,
			},
		},
	}
	if ps := psid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, psid.driver, _spec)
}

// ProductSpecsItemDeleteOne is the builder for deleting a single ProductSpecsItem entity.
type ProductSpecsItemDeleteOne struct {
	psid *ProductSpecsItemDelete
}

// Exec executes the deletion query.
func (psido *ProductSpecsItemDeleteOne) Exec(ctx context.Context) error {
	n, err := psido.psid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productspecsitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psido *ProductSpecsItemDeleteOne) ExecX(ctx context.Context) {
	psido.psid.ExecX(ctx)
}
