// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orse/ent/productattributekey"
	"orse/ent/productattributevalue"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttributeKeyCreate is the builder for creating a ProductAttributeKey entity.
type ProductAttributeKeyCreate struct {
	config
	mutation *ProductAttributeKeyMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pakc *ProductAttributeKeyCreate) SetCreatedAt(t time.Time) *ProductAttributeKeyCreate {
	pakc.mutation.SetCreatedAt(t)
	return pakc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pakc *ProductAttributeKeyCreate) SetNillableCreatedAt(t *time.Time) *ProductAttributeKeyCreate {
	if t != nil {
		pakc.SetCreatedAt(*t)
	}
	return pakc
}

// SetUpdatedAt sets the "updated_at" field.
func (pakc *ProductAttributeKeyCreate) SetUpdatedAt(t time.Time) *ProductAttributeKeyCreate {
	pakc.mutation.SetUpdatedAt(t)
	return pakc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pakc *ProductAttributeKeyCreate) SetNillableUpdatedAt(t *time.Time) *ProductAttributeKeyCreate {
	if t != nil {
		pakc.SetUpdatedAt(*t)
	}
	return pakc
}

// SetProductID sets the "product_id" field.
func (pakc *ProductAttributeKeyCreate) SetProductID(i int) *ProductAttributeKeyCreate {
	pakc.mutation.SetProductID(i)
	return pakc
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (pakc *ProductAttributeKeyCreate) SetNillableProductID(i *int) *ProductAttributeKeyCreate {
	if i != nil {
		pakc.SetProductID(*i)
	}
	return pakc
}

// SetName sets the "name" field.
func (pakc *ProductAttributeKeyCreate) SetName(s string) *ProductAttributeKeyCreate {
	pakc.mutation.SetName(s)
	return pakc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pakc *ProductAttributeKeyCreate) SetNillableName(s *string) *ProductAttributeKeyCreate {
	if s != nil {
		pakc.SetName(*s)
	}
	return pakc
}

// SetSort sets the "sort" field.
func (pakc *ProductAttributeKeyCreate) SetSort(i int) *ProductAttributeKeyCreate {
	pakc.mutation.SetSort(i)
	return pakc
}

// AddValueIDs adds the "values" edge to the ProductAttributeValue entity by IDs.
func (pakc *ProductAttributeKeyCreate) AddValueIDs(ids ...int) *ProductAttributeKeyCreate {
	pakc.mutation.AddValueIDs(ids...)
	return pakc
}

// AddValues adds the "values" edges to the ProductAttributeValue entity.
func (pakc *ProductAttributeKeyCreate) AddValues(p ...*ProductAttributeValue) *ProductAttributeKeyCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pakc.AddValueIDs(ids...)
}

// Mutation returns the ProductAttributeKeyMutation object of the builder.
func (pakc *ProductAttributeKeyCreate) Mutation() *ProductAttributeKeyMutation {
	return pakc.mutation
}

// Save creates the ProductAttributeKey in the database.
func (pakc *ProductAttributeKeyCreate) Save(ctx context.Context) (*ProductAttributeKey, error) {
	var (
		err  error
		node *ProductAttributeKey
	)
	pakc.defaults()
	if len(pakc.hooks) == 0 {
		if err = pakc.check(); err != nil {
			return nil, err
		}
		node, err = pakc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductAttributeKeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pakc.check(); err != nil {
				return nil, err
			}
			pakc.mutation = mutation
			if node, err = pakc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pakc.hooks) - 1; i >= 0; i-- {
			if pakc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pakc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pakc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pakc *ProductAttributeKeyCreate) SaveX(ctx context.Context) *ProductAttributeKey {
	v, err := pakc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pakc *ProductAttributeKeyCreate) Exec(ctx context.Context) error {
	_, err := pakc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pakc *ProductAttributeKeyCreate) ExecX(ctx context.Context) {
	if err := pakc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pakc *ProductAttributeKeyCreate) defaults() {
	if _, ok := pakc.mutation.CreatedAt(); !ok {
		v := productattributekey.DefaultCreatedAt()
		pakc.mutation.SetCreatedAt(v)
	}
	if _, ok := pakc.mutation.UpdatedAt(); !ok {
		v := productattributekey.DefaultUpdatedAt()
		pakc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pakc *ProductAttributeKeyCreate) check() error {
	if _, ok := pakc.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "sort"`)}
	}
	return nil
}

func (pakc *ProductAttributeKeyCreate) sqlSave(ctx context.Context) (*ProductAttributeKey, error) {
	_node, _spec := pakc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pakc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pakc *ProductAttributeKeyCreate) createSpec() (*ProductAttributeKey, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductAttributeKey{config: pakc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: productattributekey.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattributekey.FieldID,
			},
		}
	)
	if value, ok := pakc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productattributekey.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := pakc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productattributekey.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := pakc.mutation.ProductID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: productattributekey.FieldProductID,
		})
		_node.ProductID = value
	}
	if value, ok := pakc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: productattributekey.FieldName,
		})
		_node.Name = value
	}
	if value, ok := pakc.mutation.Sort(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: productattributekey.FieldSort,
		})
		_node.Sort = value
	}
	if nodes := pakc.mutation.ValuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productattributekey.ValuesTable,
			Columns: []string{productattributekey.ValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: productattributevalue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProductAttributeKeyCreateBulk is the builder for creating many ProductAttributeKey entities in bulk.
type ProductAttributeKeyCreateBulk struct {
	config
	builders []*ProductAttributeKeyCreate
}

// Save creates the ProductAttributeKey entities in the database.
func (pakcb *ProductAttributeKeyCreateBulk) Save(ctx context.Context) ([]*ProductAttributeKey, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pakcb.builders))
	nodes := make([]*ProductAttributeKey, len(pakcb.builders))
	mutators := make([]Mutator, len(pakcb.builders))
	for i := range pakcb.builders {
		func(i int, root context.Context) {
			builder := pakcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductAttributeKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pakcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pakcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pakcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pakcb *ProductAttributeKeyCreateBulk) SaveX(ctx context.Context) []*ProductAttributeKey {
	v, err := pakcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pakcb *ProductAttributeKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := pakcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pakcb *ProductAttributeKeyCreateBulk) ExecX(ctx context.Context) {
	if err := pakcb.Exec(ctx); err != nil {
		panic(err)
	}
}
