// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orse/ent/productattributekey"
	"orse/ent/productattributevalue"
	"orse/ent/productspecsitem"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductAttributeValueCreate is the builder for creating a ProductAttributeValue entity.
type ProductAttributeValueCreate struct {
	config
	mutation *ProductAttributeValueMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pavc *ProductAttributeValueCreate) SetCreatedAt(t time.Time) *ProductAttributeValueCreate {
	pavc.mutation.SetCreatedAt(t)
	return pavc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pavc *ProductAttributeValueCreate) SetNillableCreatedAt(t *time.Time) *ProductAttributeValueCreate {
	if t != nil {
		pavc.SetCreatedAt(*t)
	}
	return pavc
}

// SetUpdatedAt sets the "updated_at" field.
func (pavc *ProductAttributeValueCreate) SetUpdatedAt(t time.Time) *ProductAttributeValueCreate {
	pavc.mutation.SetUpdatedAt(t)
	return pavc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pavc *ProductAttributeValueCreate) SetNillableUpdatedAt(t *time.Time) *ProductAttributeValueCreate {
	if t != nil {
		pavc.SetUpdatedAt(*t)
	}
	return pavc
}

// SetKeyID sets the "key_id" field.
func (pavc *ProductAttributeValueCreate) SetKeyID(i int) *ProductAttributeValueCreate {
	pavc.mutation.SetKeyID(i)
	return pavc
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (pavc *ProductAttributeValueCreate) SetNillableKeyID(i *int) *ProductAttributeValueCreate {
	if i != nil {
		pavc.SetKeyID(*i)
	}
	return pavc
}

// SetValue sets the "value" field.
func (pavc *ProductAttributeValueCreate) SetValue(s string) *ProductAttributeValueCreate {
	pavc.mutation.SetValue(s)
	return pavc
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (pavc *ProductAttributeValueCreate) SetNillableValue(s *string) *ProductAttributeValueCreate {
	if s != nil {
		pavc.SetValue(*s)
	}
	return pavc
}

// SetSort sets the "sort" field.
func (pavc *ProductAttributeValueCreate) SetSort(i int) *ProductAttributeValueCreate {
	pavc.mutation.SetSort(i)
	return pavc
}

// SetKey sets the "key" edge to the ProductAttributeKey entity.
func (pavc *ProductAttributeValueCreate) SetKey(p *ProductAttributeKey) *ProductAttributeValueCreate {
	return pavc.SetKeyID(p.ID)
}

// AddItemIDs adds the "items" edge to the ProductSpecsItem entity by IDs.
func (pavc *ProductAttributeValueCreate) AddItemIDs(ids ...int) *ProductAttributeValueCreate {
	pavc.mutation.AddItemIDs(ids...)
	return pavc
}

// AddItems adds the "items" edges to the ProductSpecsItem entity.
func (pavc *ProductAttributeValueCreate) AddItems(p ...*ProductSpecsItem) *ProductAttributeValueCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pavc.AddItemIDs(ids...)
}

// Mutation returns the ProductAttributeValueMutation object of the builder.
func (pavc *ProductAttributeValueCreate) Mutation() *ProductAttributeValueMutation {
	return pavc.mutation
}

// Save creates the ProductAttributeValue in the database.
func (pavc *ProductAttributeValueCreate) Save(ctx context.Context) (*ProductAttributeValue, error) {
	var (
		err  error
		node *ProductAttributeValue
	)
	pavc.defaults()
	if len(pavc.hooks) == 0 {
		if err = pavc.check(); err != nil {
			return nil, err
		}
		node, err = pavc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductAttributeValueMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pavc.check(); err != nil {
				return nil, err
			}
			pavc.mutation = mutation
			if node, err = pavc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pavc.hooks) - 1; i >= 0; i-- {
			if pavc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pavc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pavc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pavc *ProductAttributeValueCreate) SaveX(ctx context.Context) *ProductAttributeValue {
	v, err := pavc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pavc *ProductAttributeValueCreate) Exec(ctx context.Context) error {
	_, err := pavc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pavc *ProductAttributeValueCreate) ExecX(ctx context.Context) {
	if err := pavc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pavc *ProductAttributeValueCreate) defaults() {
	if _, ok := pavc.mutation.CreatedAt(); !ok {
		v := productattributevalue.DefaultCreatedAt()
		pavc.mutation.SetCreatedAt(v)
	}
	if _, ok := pavc.mutation.UpdatedAt(); !ok {
		v := productattributevalue.DefaultUpdatedAt()
		pavc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pavc *ProductAttributeValueCreate) check() error {
	if _, ok := pavc.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "sort"`)}
	}
	return nil
}

func (pavc *ProductAttributeValueCreate) sqlSave(ctx context.Context) (*ProductAttributeValue, error) {
	_node, _spec := pavc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pavc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pavc *ProductAttributeValueCreate) createSpec() (*ProductAttributeValue, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductAttributeValue{config: pavc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: productattributevalue.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productattributevalue.FieldID,
			},
		}
	)
	if value, ok := pavc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productattributevalue.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := pavc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: productattributevalue.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := pavc.mutation.Value(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: productattributevalue.FieldValue,
		})
		_node.Value = value
	}
	if value, ok := pavc.mutation.Sort(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: productattributevalue.FieldSort,
		})
		_node.Sort = value
	}
	if nodes := pavc.mutation.KeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   productattributevalue.KeyTable,
			Columns: []string{productattributevalue.KeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: productattributekey.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.KeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pavc.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   productattributevalue.ItemsTable,
			Columns: productattributevalue.ItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: productspecsitem.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProductAttributeValueCreateBulk is the builder for creating many ProductAttributeValue entities in bulk.
type ProductAttributeValueCreateBulk struct {
	config
	builders []*ProductAttributeValueCreate
}

// Save creates the ProductAttributeValue entities in the database.
func (pavcb *ProductAttributeValueCreateBulk) Save(ctx context.Context) ([]*ProductAttributeValue, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pavcb.builders))
	nodes := make([]*ProductAttributeValue, len(pavcb.builders))
	mutators := make([]Mutator, len(pavcb.builders))
	for i := range pavcb.builders {
		func(i int, root context.Context) {
			builder := pavcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductAttributeValueMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pavcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pavcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pavcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pavcb *ProductAttributeValueCreateBulk) SaveX(ctx context.Context) []*ProductAttributeValue {
	v, err := pavcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pavcb *ProductAttributeValueCreateBulk) Exec(ctx context.Context) error {
	_, err := pavcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pavcb *ProductAttributeValueCreateBulk) ExecX(ctx context.Context) {
	if err := pavcb.Exec(ctx); err != nil {
		panic(err)
	}
}
