// Code generated by entc, DO NOT EDIT.

package ent

import (
	"orse/ent/menu"
	"orse/ent/order"
	"orse/ent/orderpay"
	"orse/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	menuMixin := schema.Menu{}.Mixin()
	menuMixinFields1 := menuMixin[1].Fields()
	_ = menuMixinFields1
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreatedAt is the schema descriptor for created_at field.
	menuDescCreatedAt := menuMixinFields1[0].Descriptor()
	// menu.DefaultCreatedAt holds the default value on creation for the created_at field.
	menu.DefaultCreatedAt = menuDescCreatedAt.Default.(func() time.Time)
	// menuDescUpdatedAt is the schema descriptor for updated_at field.
	menuDescUpdatedAt := menuMixinFields1[1].Descriptor()
	// menu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menu.DefaultUpdatedAt = menuDescUpdatedAt.Default.(func() time.Time)
	// menu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menu.UpdateDefaultUpdatedAt = menuDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menuDescLevel is the schema descriptor for level field.
	menuDescLevel := menuFields[3].Descriptor()
	// menu.DefaultLevel holds the default value on creation for the level field.
	menu.DefaultLevel = menuDescLevel.Default.(int)
	// menuDescSort is the schema descriptor for sort field.
	menuDescSort := menuFields[4].Descriptor()
	// menu.DefaultSort holds the default value on creation for the sort field.
	menu.DefaultSort = menuDescSort.Default.(int)
	orderMixin := schema.Order{}.Mixin()
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderMixinFields0[0].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderMixinFields0[1].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	orderpayMixin := schema.OrderPay{}.Mixin()
	orderpayMixinFields0 := orderpayMixin[0].Fields()
	_ = orderpayMixinFields0
	orderpayFields := schema.OrderPay{}.Fields()
	_ = orderpayFields
	// orderpayDescCreatedAt is the schema descriptor for created_at field.
	orderpayDescCreatedAt := orderpayMixinFields0[0].Descriptor()
	// orderpay.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderpay.DefaultCreatedAt = orderpayDescCreatedAt.Default.(func() time.Time)
	// orderpayDescUpdatedAt is the schema descriptor for updated_at field.
	orderpayDescUpdatedAt := orderpayMixinFields0[1].Descriptor()
	// orderpay.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderpay.DefaultUpdatedAt = orderpayDescUpdatedAt.Default.(func() time.Time)
	// orderpay.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderpay.UpdateDefaultUpdatedAt = orderpayDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderpayDescCreateID is the schema descriptor for create_id field.
	orderpayDescCreateID := orderpayFields[1].Descriptor()
	// orderpay.DefaultCreateID holds the default value on creation for the create_id field.
	orderpay.DefaultCreateID = orderpayDescCreateID.Default.(int)
	// orderpayDescPrice is the schema descriptor for price field.
	orderpayDescPrice := orderpayFields[3].Descriptor()
	// orderpay.DefaultPrice holds the default value on creation for the price field.
	orderpay.DefaultPrice = orderpayDescPrice.Default.(float64)
}
