// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderPay is the predicate function for orderpay builders.
type OrderPay func(*sql.Selector)
